elearningplatform/core/urls.py
from django.urls import path
from .views import HomeView


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
]

elearningplatform/elearningplatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('subject/', include('subject.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    # Admin
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elearningplatform/profiles/urls.py
from django.urls import path
from .views import ProfilesListView, ProfileDetailView, ProfileStudentUpdate


urlpatterns = [
    path('', ProfilesListView.as_view(), name="profiles"),
    path('<int:id>/', ProfileDetailView.as_view(), name="profiles"),
    path('student/<int:id>/', ProfileStudentUpdate.as_view(), name="student-update"),
]

elearningplatform/registration/urls.py
from django.urls import path
from .views import TeacherView, StudentView, ProfileUpdate

urlpatterns = [
    path('teacher_signup/', TeacherView, name="teacher_signup"),
    path('student_signup/', StudentView, name="student_signup"),
    path('profile/', ProfileUpdate.as_view(), name='profile'),
]

elearningplatform/subject/urls.py
from django.urls import path
from .views import SubjectView, SubjectListView, SubjectDetailView, FileView, FileDetailView, FileDeleteView, SubjectDeleteView


urlpatterns = [
    path('', SubjectListView.as_view(), name="subject"),
    path('<int:pk>/', SubjectDetailView.as_view(), name="subject"),
    path('new-subject', SubjectView.as_view(), name="new-subject"),
    path('delete-subject/<int:pk>', SubjectDeleteView.as_view(), name="delete-subject"),
    path('new-file/<int:id>', FileView, name="new-file"),
    path('file/<int:pk>', FileDetailView.as_view(), name="file"),
    path('delete-file/<int:pk>', FileDeleteView.as_view(), name="delete-file"),
]

elearningplatform/core/models.py
from django.db import models

# Create your models here.

elearningplatform/profiles/models.py
from django.db import models

# Create your models here.

elearningplatform/subject/models.py
from django.db import models


# Create your models here.
class Subject(models.Model):
    name = models.CharField(max_length=200, verbose_name="Subject")
    image = models.ImageField(null=True, blank=True, upload_to="subject", verbose_name="Image")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")
    updated = models.DateTimeField(auto_now=True, verbose_name="Update Date")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class File(models.Model):
    name = models.CharField(max_length=25, verbose_name="Name")
    description = models.TextField(max_length=200, null=True, blank=True, verbose_name="Description")
    file = models.FileField(upload_to="file", verbose_name="File")
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, verbose_name="Subject")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Creation Date")
    updated = models.DateTimeField(auto_now=True, verbose_name="Update Date")

    class Meta:
        ordering = ["-created"]

elearningplatform/subject/forms.py
from django import forms
from .models import Subject, File


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ["name", "image"]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Subject name'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file mt-3'}),
        }


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['name', 'description', 'file']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'File Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'File Description'}),
            'file': forms.FileInput()
        }

elearningplatform/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class HomeView(TemplateView):
    template_name = "core/home.html"

elearningplatform/profiles/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from registration.models import Profile
from registration.forms import StudentForm


# Create your views here.
class ProfilesListView(ListView):
    model = Profile
    template_name = "profiles/profile_list.html"
    paginate_by = 20


class ProfileDetailView(DetailView):
    model = Profile
    template_name = "profiles/profile_detail.html"

    def get_object(self):
        return get_object_or_404(Profile, user__id=self.kwargs['id'])


class ProfileStudentUpdate(UpdateView):
    form_class = StudentForm
    template_name = 'profiles/profile_student_update.html'
    success_url = reverse_lazy('profiles')

    # Get the student profile
    def get_object(self):
        return get_object_or_404(Profile, user__id=self.kwargs['id'])

elearningplatform/subject/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Subject, File
from .forms import SubjectForm, FileForm


# Decorator for teacher links only
def teacher_access(user):
    user_logged = user.profile.is_teacher
    if user_logged:
        return True
    return False


class TeacherRequiredMixin(object):
    @method_decorator(user_passes_test(teacher_access))
    def dispatch(self, request, *args, **kwargs):
        return super(TeacherRequiredMixin, self).dispatch(request, *args, **kwargs)


# SUBJECTS
@method_decorator(login_required, name='dispatch')
class SubjectListView(ListView):
    model = Subject
    template_name = "subject/subject_list.html"


@method_decorator(login_required, name='dispatch')
class SubjectDetailView(DetailView):
    model = Subject
    template_name = "subject/subject_detail.html"


@method_decorator(login_required, name='dispatch')
class SubjectView(TeacherRequiredMixin, CreateView):
    model = Subject
    success_url = reverse_lazy('home')
    form_class = SubjectForm
    template_name = "subject/subject_form.html"


@method_decorator(login_required, name='dispatch')
class SubjectDeleteView(TeacherRequiredMixin, DeleteView):
    model = Subject
    success_url = reverse_lazy('subject')


# FILES
@method_decorator(login_required, name='dispatch')
class FileDetailView(DetailView):
    model = File


@login_required
@user_passes_test(teacher_access)
def FileView(request, id):
    if request.user.is_authenticated:
        file_form = FileForm()
        if request.method == "POST":
            file_form = FileForm(request.POST, request.FILES)
            if file_form.is_valid():
                form = file_form.save(commit=False)
                form.subject_id = id
                form.save()
            return redirect('subject', pk=id)
        return render(request, "subject/file_form.html", {'file_form': file_form})
    else:
        return redirect(reverse_lazy('login'))


@method_decorator(login_required, name='dispatch')
class FileDeleteView(TeacherRequiredMixin, DeleteView):
    model = File
    success_url = reverse_lazy('subject')

elearningplatform/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Styles -->
    <link rel="icon" type="image/x-icon" href="{% static 'core/img/favicon.ico' %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
</head>
<body>

<!-- Navbar-->
<nav class="navbar navbar-expand-lg navbar-purple">

    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="navbar-brand btn btn-sm navbar-green" aria-current="page" href="{% url 'home' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                             class="bi bi-house-door-fill" viewBox="-5 1 20 20">
                            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5"/>
                        </svg>
                        Home
                    </a>
                </li>

            </ul>
            <ul class="navbar-nav mr-auto">
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link btn btn-sm navbar-green" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button class="nav-link btn btn-sm navbar-pink" type="submit">Logout</button>
                    </form>
                </li>
                <li class="nav-link navbar-yellow"> {{request.user}}</li>
                <li class="nav-item">
                    <a href="{% url 'profile' %}">
                        {% if request.user.profile.avatar %}
                        <img src="{{request.user.profile.avatar.url}}" class="img-avatar rounded-circle">
                        {% else %}
                        {% if request.user.profile.is_teacher %}
                        <img src="{% static 'core/img/no-avatar-teacher.png' %}" class="img-avatar rounded-circle">
                        {% else %}
                        <img src="{% static 'core/img/no-avatar-student.png' %}" class="img-avatar rounded-circle">
                        {% endif %}
                        {% endif %}
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Sidebar-->

<div class="wrapper">
    {% if request.user.is_authenticated %}
    <div class="d-flex flex-shrink-0 p-3 col-auto" id="sidebar">

        <ul class="nav nav-pills flex-column mb-auto">
            <a href="{% url 'subject' %}" class="nav-link fs-5 sidebar-text-color">
                <i class="bi bi-folder"></i>
                <span class="d-none d-sm-inline">My Subjects</span>

            </a>

            {% for subject in request.user.profile.subjects.all %}
            <li>
                <a href="{% url 'subject' subject.id %}" class="nav-link sidebar-text-color fs-6">
                    <i class="bi bi-book"></i>
                    <span class="d-none d-sm-inline">{{subject}}</span>
                </a>
            </li>
            {% endfor %}
            {% if request.user.profile.is_teacher %}
            <hr>
            <li>
                <a href="{% url 'new-subject' %}" class="nav-link sidebar-text-register" aria-expanded="false">
                    <i class="bi bi-folder-plus"></i>
                    <span class="d-none d-sm-inline">New Subjec</span>
                </a>
            </li>
            <li>
                <a href="{% url 'teacher_signup' %}" class="nav-link sidebar-text-register" aria-expanded="false">
                    <i class="bi bi-person-plus-fill"></i>
                    <span class="d-none d-sm-inline">Register New Teacher</span>
                </a>
            </li>
            <li>
                <a href="{% url 'student_signup' %}" class="nav-link sidebar-text-register" aria-expanded="false">
                    <i class="bi bi-person-plus"></i>
                    <span class="d-none d-sm-inline">Register New Student</span>
                </a>
            </li>

            <hr>
            <li>
                <a href="{% url 'profiles' %}" class="nav-link sidebar-text-register" aria-expanded="false">
                    <i class="bi bi-search"></i>
                    <span class="d-none d-sm-inline">My Students</span>
                </a>
            </li>

            {% endif %}
        </ul>
    </div>
    {% endif %}
    {% block content %}{% endblock %}
</div>


<!-- Footer -->
<footer>
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="small text-center fst-italic">&copy;<span id="currentYear"></span> arenaf  </div>
        </div>
    </div>
</footer>
<script type="text/javascript">
    document.getElementById("currentYear").innerHTML = new Date().getFullYear()
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

elearningplatform/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block content%}

    <div class="container">
        <div class="img-home">
           <img src="{% static 'core/img/home-bg.png' %}">
        </div>
    </div>

{% endblock %}

elearningplatform/profiles/templates/profiles/profile_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content%}

<div class="container mb-4">
    <div class="row mt-3">
        <div class="col-md-9 mx-auto">
            <div class="row mt-4">
                <div class="col-md-2">
                    {% if profile.avatar %}
                        <img src="{{profile.avatar.url}}" class="img-fluid">
                    {% else %}
                    {% if profile.is_teacher %}
                        <img src="{% static 'core/img/no-avatar-teacher.png' %}" class="img-fluid">
                    {% else %}
                        <img src="{% static 'core/img/no-avatar-student.png' %}" class="img-fluid">
                    {% endif %}
                    {% endif %}
                    <p><a href="{% url 'profiles' %}" type="button" class="btn btn-color-profile mt-5"> Profiles </a></p>
                </div>
                <div class="col-md-10">
                    <h2 class="mb-4 title-text"> {{profile.user}}</h2>
                    <h4 class="text-profile">Subjects:</h4>
                    {% for subject in profile.subjects.all %}
                        <p>{{subject}}</p>
                    {% endfor %}
                    <p><a href="{% url 'student-update' profile.user.id %}" type="button" class="btn btn-color-profile mt-5 float-end"> Update Subjects</a></p>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

elearningplatform/profiles/templates/profiles/profile_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}


<style>.profile-avatar{float:left;width:4rem;height:4rem}.profile-data{padding-left:4.5rem;padding-top:.4rem;}</style>
    <div class="container">
        <div class="row mt-3 ">
          <div class="col-md-9 mx-auto mb-5">
            <h2 class="title-text mb-5 mt-3">My students</h2>
            <div class="row">
                {% for profile in object_list %}
                {% if profile in request.user.profile.students.all %}
                    <div class="col-md-4 mt-2 mb-3 ">
                        <div class="row p-1">
                            <div class="col-md-12">
                                {% if profile.avatar %}
                                    <img src="{{profile.avatar.url}}" class="img-fluid profile-avatar">
                                {% else %}
                                    {% if profile.is_teacher %}
                                        <img src="{% static 'core/img/no-avatar-teacher.png' %}" class="img-fluid profile-avatar" >
                                    {% else %}
                                        <img src="{% static 'core/img/no-avatar-student.png' %}" class="img-fluid profile-avatar">
                                    {% endif %}
                                {% endif %}
                                <p class="profile-data">
                                    <b class="text-profile">{{profile.user|truncatechars:"15"}}</b><br>
                                    <a href="{% url 'profiles' profile.user.id %}" class="text-profile">See Profile</a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endif %}
                {% endfor %}
            </div>
          </div>
        </div>

        {% if is_paginated %}
            <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item ">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">&laquo;</a>
                </li>
                {% endif %}
                {% for i in paginator.page_range %}
                <li class="page-item {% if page_obj.number == i %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">&raquo;</a>
                </li>
                {% endif %}
            </ul>
            </nav>
            {% endif %}


    </div>

{% endblock %}

elearningplatform/profiles/templates/profiles/profile_student_update.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block content%}

<script>
  function updateConfirm() {
    alert("Profile updated successfully")
  }
</script>

<div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <div class="row mt-4">


            <div class="col-md-10">
              <h3 class="mb-4 title-text">{{profile.user}}</h3>

                {{ form.subjects }}


              <input type="submit" class="btn btn-color mt-4" onclick="updateConfirm()" value="Update Profile">

          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

elearningplatform/subject/templates/subject/file_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}

<div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <h2 class="section-heading mb-4 title-text mt-5">Do you want to delete the file "{{ object.name }}"?</h2>
                <input type="submit" class="btn btn-lg btn-color" value="Yes" />
                <a href="{% url 'subject' %}" class="btn btn-lg btn-delete">No </a>
            </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

elearningplatform/subject/templates/subject/file_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}

<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-md-9 mx-auto">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-text title-text mb-4">Name: {{file.name}}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary">Description: </h6>
                    <p class="text-body-secondary">{{file.description}}</p>
                    <p><a href="{{file.file.url}}" download type="button" class="btn btn-sm btn-color">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-download" viewBox="0 0 18 18">
                          <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
                          <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                        </svg>
                        Download
                        </a>
                        {% if request.user.profile.is_teacher %}
                        <a href="{% url 'delete-file' file.id %}" class="btn btn-sm btn-delete-item">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 18 18">
                              <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                            </svg>
                            Delete
                        </a>
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

elearningplatform/subject/templates/subject/file_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Upload file{% endblock %}
{% block content%}
<style>.errorlist{color:#ef476f;} label{display:none}</style>

  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <h3 class="mb-4 title-text">Upload file</h3>
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          <p>
            {{file_form.as_p}}
          </p>
          <p><input type="submit" class="btn btn-color" value="Submit"></p>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

elearningplatform/subject/templates/subject/subject_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}

<div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <h2 class="section-heading mb-4 title-text mt-5">Do you want to delete the subject "{{ object.name }}"?</h2>
                <input type="submit" class="btn btn-lg btn-color" value="Yes" />
                <a href="{% url 'subject' %}" class="btn btn-lg btn-delete">No </a>
            </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

elearningplatform/subject/templates/subject/subject_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}

<div class="container">
    <div class="row mt-3">
        <div class="col-md-9 mx-auto">
            <h2 class="section-heading mb-4 title-text">{{subject.name}}</h2>
            <div class="list-group list-group-flush mb-3">
                {% for file in object.file_set.all %}
                  <a href="{% url 'file' file.id %}"
                     class="list-group-item list-group-item-action flex-column align-items-start">
                      <div class="d-flex w-100 justify-content-between">
                          <p class="mb-1 ">{{file.name}}</p>
                          <small>{{file.description}}</small>
                      </div>
                  </a>
                {% endfor %}
            </div>
            {% if request.user.profile.is_teacher %}
            <div>
                <p><a href="{% url 'new-file' subject.id %}" type="button" class="btn btn-color mb-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-file-earmark-plus" viewBox="0 0 16 16">
                        <path d="M8 6.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 .5-.5"/>
                        <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>
                    </svg>
                    Add file
                </a></p>
            </div>
            <div>
                <p><a href="{% url 'delete-subject' subject.id %}" type="button"
                      class="btn btn-sm btn-delete-item mb-3 float-end">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                         class="bi bi-trash3-fill" viewBox="0 0 18 18">
                        <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5m-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5M4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06m6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528M8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5"/>
                    </svg>
                    Delete Subject
                </a></p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

elearningplatform/subject/templates/subject/subject_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}
<style>.errorlist{color:#ef476f;} label{display:none}</style>

  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <h3 class="mb-4 title-text">New Subject</h3>
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
          {{form.as_p}}
          <p><input type="submit" class="btn btn-color" value="Submit"></p>
        </form>
      </div>
    </div>
  </div>


{% endblock %}

elearningplatform/subject/templates/subject/subject_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}New subject{% endblock %}
{% block content%}

<div class="container">
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 py-3">
    {% for subject in request.user.profile.subjects.all %}
      <div class="col">
        <div class="card shadow-sm" style="width: 18rem;">
          <div class="img-highlight">
            <a href="{% url 'subject' subject.id %}">
              {% if subject.image %}
                <img src="{{subject.image.url}}" alt="img-subject" border="0" class="d-block mx-lg-auto img-fluid"
                     width="300em" loading="lazy"/>
              {% else %}
                <img src="{% static 'core/img/no-subject.png' %}" alt="img-subject" border="0" class="d-block mx-lg-auto img-fluid"
                     width="300em" loading="lazy"/>
              {% endif %}
            </a>
          </div>
          <div class="card-body">
            <h5 class="card-text text-card-color">{{subject}}</h5>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>


{% endblock %}